[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Needed for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
